apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testservice
spec:
  ingressClassName: nginx
  rules:
  - host: projectxconsulting.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testservice
            port:
              number: 80
              
